name: React Build and Test
run-name: Running Test For Frontend
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install
        working-directory: mobisandals/frontend

    #   - name: Build
    #     run: npm run build

      - name: Test
        run: npm test
        working-directory: mobisandals/frontend
